apiVersion: v1
kind: Pod
metadata:
  name: nginx1
  namespace: ns1
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  - name: tomcat
    image: tomcat
    ports:
    - containerPort: 8080

