apiVersion: v1
kind: Service
metadata:
  name: tomcat-service1
spec:
  type: NodePort
  selector:
    app: tomcat
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    nodePort: 32001
    targetPort: 8080 

